version: '3'

services:
  node:
    build: .
    networks:
      - custom-net
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: on-failure
    volumes:
       - ./src:/app/src
      - ./logs:/app/logs
    environment:
      PORT: ${PORT}

  postgres:
    build: ./database/
    networks:
      - custom-net
    ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: on-failure
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}   
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PORT: ${POSTGRES_PORT}

networks:
  custom-net:
    driver: bridge

volumes:
  pgdata:
  # src:
  # logs: